[package]
name = "chrom-proxy"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
tokio-rustls = "0.23"
rustls-pemfile = "1.0"
base64 = "0.13"
reqwest = { version = "0.11", features = ["json"] }
