[package]
name = "chrom-proxy"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.28", features = ["full"] }
tokio-rustls = "0.24"
rustls-pemfile = "1.0"
base64 = "0.21"
reqwest = { version = "0.11", features = ["json"] }
rustls = "0.21"  # 添加 rustls 依赖
