name: Build and Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: '版本标签'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: 设置Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        
    - name: 构建
      run: cargo build --release
      
    - name: 获取二进制文件名
      id: get_binary
      run: |
        BINARY_NAME=$(ls target/release | grep -v '\.d$' | grep -v '\.rlib$' | head -n 1)
        echo "BINARY_NAME=$BINARY_NAME" >> $GITHUB_OUTPUT
        echo "二进制文件名是: $BINARY_NAME"
        
    - name: 创建Release并上传二进制文件
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release create ${{ github.event.inputs.version }} \
          --title "${{ github.event.inputs.version }}" \
          --notes "Release ${{ github.event.inputs.version }}" \
          ./target/release/${{ steps.get_binary.outputs.BINARY_NAME }}
