name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --release
    - name: Release
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release create ${{ github.event.inputs.version }} \
          --title "${{ github.event.inputs.version }}" \
          --notes "Release ${{ github.event.inputs.version }}" \
          ./target/release/YOUR_BINARY_NAME
